# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImageFusion
                                 A QGIS plugin
 This plugin is a UI interface for the Image Fusion plugin.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-08-16
        copyright            : (C) 2021 by AUG Signals
        email                : tomas@augsignals.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImageFusion class from file ImageFusion.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .image_fusion import ImageFusion
    return ImageFusion(iface)
