# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EdgeDetection
                                 A QGIS plugin
 This plugin performs edge detection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-24
        copyright            : (C) 2020 by Tomas
        email                : tomas@augsignals.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EdgeDetection class from file EdgeDetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .edge_detection import EdgeDetection
    return EdgeDetection(iface)
