# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SettingsConfiguration
                                 A QGIS plugin
 This plugin manages settings for AUG plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-01
        copyright            : (C) 2020 by Chris
        email                : chris@augsignals.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SettingsConfiguration class from file SettingsConfiguration.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .settings_configuration import SettingsConfiguration
    return SettingsConfiguration(iface)
